### ISSUE TITLE
Error at loading document into Curation

### ISSUE THREAD

**Issue by sblss** [webanno/webanno#990]
When I try to load a document into Curation, I get two Error messages: "Unable to determine project state." and "Unable to load data: FileNotFoundException: Annotation document of user [CURATION_USER] for source document [1903_Zwei Menschen..txt] (0) not found in project[Testprojekt1] (0)"
In "Monitoring", it is shown that the document is finished by all annotators, but the link to Curation there does not work as well, since it leads to an internal error. The annotators still can open the document in the Annotation-module, so I'm not sure why it does not work in Curation.
I use the standalone version 3.4.2 and I got the JAR on the WebAnno-download-page.
Attached, you finde the whole action of the command window (starting at the login process and then trying to open the document in Curation) - sorry, I'm not sure what of this is important to solve the problem.
[Commands curation.txt](https://github.com/webanno/webanno/files/2102837/Commands.curation.txt)

**Comment by reckart** [comment]
Thanks for the report. Looking into it.

**Comment by reckart** [comment]
There is a bug in the code. I am looking how to fix it.

Meanwhile, you should be able to get around the problem by uploading an additional document, opening it once in the annotation editor page and **not** mark it as finished.

**Comment by reckart** [comment]
I fixed a bug in the calculation of the project state and I assume that the error `Caused by: java.io.FileNotFoundException: Annotation document of user [CURATION_USER] for source document [1903_Zwei Menschen..txt] (0) not found in project[Testprojekt1] (0)` is a follow up error that should no longer appear after the project state calculation is fixed.

**Comment by sblss** [comment]
It works with loading up another document, so I can go on working now, but without this upload, I get the same error-notifications.

**Comment by reckart** [comment]
The code which calculates the overall state of a project in WebAnno 3.4.2 has a bug in that it doesn't consider the case where all documents in a project are either new or finished. I will release WebAnno 3.4.3 with a fix for this issue on the weekend - that should remove the need for the workaround for you.

**Comment by sblss** [comment]
Alright, thanks a lot!

2018-06-15 14:13 GMT+02:00 Richard Eckart de Castilho <
notifications@github.com>:

**Comment by j-lnaddef** [comment]
@reckart Has the fix been merged into the master branch? I got the same issue so I updated the sources but I still get the `java.lang.IllegalStateException: Unable to determine project state.`

**Comment by reckart** [comment]
@j-lnaddef it should be fixed. Which commit/version are you using?

**Comment by j-lnaddef** [comment]
```
commit 8ec543504f252a01aabbf1ea68e96b37e40c1ce0
Merge: 0fcf4c4 257b13a
Author: Richard Eckart de Castilho <richard.eckart@gmail.com>
Date:   Wed Jun 27 18:12:20 2018 +0200

    Empty merge of branch '3.4.x' after release.

**Comment by j-lnaddef** [comment]
But the exception is a little bit different from before I believe. Before it was something like `ArrayOutOfBoundException, 0 index in arr[0]` (pretty innacurate sorry, do not remember exactly), and now it is `Caused by: java.io.FileNotFoundException: CAS [{},{}] does not exist and no initializer is specified.`

**Comment by reckart** [comment]
Hmm.... Since you build from source, could you change edit the source file `webanno-project/srv/main/java/de/tudarmstadt/ukp/clarin/webanno/project/SourceDocumentStateStats.java` and in the method `getProjectState()` change line 92 from:

```
90:  else {
91:    // This should actually never happen...
92:    throw new IllegalStateException("Unable to determine project state.");
92:  }
```

to 

```
90:  else {
91:    // This should actually never happen...
92:    throw new IllegalStateException("Unable to determine project state. " + toString());
92:  }
```

Then try to trigger the exception again and post the error message. That should help me seeing in what state your project is and why WebAnno isn't able to make sense of it.

**Comment by reckart** [comment]
@j-lnaddef mind that master has seen some refactorings recently that are still being tested. I will do a beta release soonish, but it's still some time before master will be released. Unless you have a good reason, you should rather stick to the 3.4.x branch.

**Comment by reckart** [comment]
It could be possible that as part of the export or import, WebAnno has internally created more state information that eventually allowed it to properly calculate the source document state. My guess would be that we probably still have a bug somewhere but it is hard to track.

If you come across it again, please let me know.

**Comment by reckart** [comment]
@j-lnaddef please keep the project around on your dev instance - I'll try to add some more helpful output to the error message.

**Comment by reckart** [comment]
@j-lnaddef This this issue is already closed and the version is released, I have opened a new issue here: #1011

Let's continue to discuss here.
